apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: websecure
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: dashboard 
      port: 8080
      targetPort: 8080  
      nodePort: 30090  # for access traefik ui
